### PR TITLE
[TestPlans] Hide all expanded children, fixes #3245

### LINKED ISSUE #3245: Child Test Plan does not collapse when parent collapses
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem

If a second-level test plan has a nested test plan, then when the first-level test plan is collapsed, the second-level test plan won't be collapsed. It's better to see what I mean in the screenshots.

1. Initial conditions. A and B are expanded:
image

2. After A collapses, C stays on screen:
image

3. When you expand A again, C is now on the end of list, B is not collapsed:
image

### Version or commit hash (if applicable)

12.4

### Steps to Reproduce

1. Create test plans with structure Parent->Child1->Child2.
2. In Search Test Plans tab expand Parent and Child1 test plans.
3. Collapse Parent test plan, Child2 will be still on the list.

### Actual results

Nested child test plans aren't collapsed when parent is collapsed.

### Expected results

Nested child test plans are collapsed when parent is collapsed. Or works as hierarchy view on Test Plan page.

### Additional info (Python traceback, logs, etc.)

Link to tested plans: https://public.tenant.kiwitcms.org/plan/7637/a

### PR DESCRIPTION
**Pull request by somenewacc**
Recursively find all expanded children of parentRow and hide them.

### CODE REVIEW

File: tcms/testplans/static/testplans/js/search.js [hunk 1]
```diff
@@ -172,6 +170,24 @@ export function pageTestplansSearchReadyHandler () {
     $('#id_product').change(updateVersionSelectFromProduct)
 }
 
+function hideExpandedChildren (table, parentRow) {
+    const children = hiddenChildRows[parentRow.data().id]
+    if (!children) {
+        return
+    }
```
Comment (atodorov) [inline tcms/testplans/static/testplans/js/search.js:177]: I think this is redundant. When `children` is empty the loop below will not iterate and the function will exit anyway.

**Review by atodorov — CHANGES_REQUESTED** [review]
Minor change requested

File: tcms/testplans/static/testplans/js/search.js (hunk 1 above)
Comment (somenewacc) [reply tcms/testplans/static/testplans/js/search.js:177]: @atodorov 
If `parentRow.data().id` not in `hiddenChildRows` childer will be `undefined` and then it will crash.

I don't know if this is a possible situation, what do you think?

Comment (atodorov) [reply tcms/testplans/static/testplans/js/search.js:177]: > If parentRow.data().id not in hiddenChildRows

That's not supposed to happen, see line 129-135. That would mean you are trying to collapse a row which has no children to begin with, so it shouldn't be expanded in the first place.  If that happens there is probably a bug somewhere else, not in the `hideExpandedChildren()` function. Let it crash if that's the case so we can see it and fix it.

Comment (somenewacc) [reply tcms/testplans/static/testplans/js/search.js]: Fair. Fixed
