### PR TITLE
Fixes #2145: Fixes removing a component from a TestCase

### LINKED ISSUE #2145: Internal Error: Field 'id' expected a number but got 'undefined' when remove a component on testcase page
HINT: try to reproduce bugs and errors at https://public.tenant.kiwitcms.org!
This is always running the latest version and will automatically submit
traceback and debugging information to us!

### Description of problem
It shows Internal Error: Field 'id' expected a number but got 'undefined' when remove component on testcase page.

### Version or commit hash (if applicable)
https://public.tenant.kiwitcms.org/case/10227/#components

### Steps to Reproduce

1. Open a testcase, e.g: https://public.tenant.kiwitcms.org/case/10227
2. Add a component (which doesn't reload the page)
3. Click remove the recent added component

### Actual results
a error popup will show.

### Expected results
remove the component

### Additional info (Python traceback, logs, etc.)
I can remove the component if reload the page.
remove_component

### PR DESCRIPTION
**Pull request by pandafy**
Breaking Change: Modifies return information of "TestCase.add_component"
RPC API

Closes #2145

### CODE REVIEW

File: tcms/testcases/static/testcases/js/get.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ function addComponent(object_id, _input, to_table) {
     if (_name.length > 0) {
         jsonRPC('TestCase.add_component', [object_id, _name], function(data) {
             if (data !== undefined) {
-                to_table.row.add({name: _name}).draw();
+                to_table.row.add({name: data.name, id: data.id}).draw();
```
Comment (pandafy) [inline tcms/testcases/static/testcases/js/get.js:10]: I have substituted `_name` with `data.name` to make it uniform.

File: tcms/rpc/tests/test_testcase.py [hunk 2]
```diff
@@ -651,7 +651,7 @@ def test_add_component_from_same_product_is_allowed(self):
         result = self.rpc_client.TestCase.add_component(
             self.test_case.pk, self.good_component.name
         )
-        self.assertEqual(result["component"][0], self.good_component.pk)
+        self.assertEqual(result["id"], self.good_component.pk)
```
Comment (atodorov) [inline tcms/rpc/tests/test_testcase.py:654]: Can you cherry-pick https://github.com/kiwitcms/Kiwi/commit/101f725b3db90c6e2d3b0e6396958002a952a8dd instead and then add the front-end fixes as a separate commit inside this PR.

File: tcms/testcases/static/testcases/js/get.js (hunk 1 above)
Comment (atodorov) [inline tcms/testcases/static/testcases/js/get.js:10]: If I understand this correctly the second argument goes into the second column in the table. What if we want to add more columns or change their order in the future? Can we tie the field name "id" to the column with the delete button somehow (see lines 106-118) ?

**Review by atodorov — CHANGES_REQUESTED** [review]

File: tcms/rpc/tests/test_testcase.py (hunk 2 above)
Comment (pandafy) [reply tcms/rpc/tests/test_testcase.py:654]: I see that https://github.com/kiwitcms/Kiwi/commit/101f725b3db90c6e2d3b0e6396958002a952a8dd does not belongs to any branch. I have used https://github.com/kiwitcms/Kiwi/commit/ce3fb53bc4761b958bff9c63d0818d4e5909545b instead.

File: tcms/testcases/static/testcases/js/get.js (hunk 1 above)
Comment (pandafy) [reply tcms/testcases/static/testcases/js/get.js:10]: I went through the documentation of DataTables plugin. According to ["Renderers"](https://www.datatables.net/manual/data/renderers) and [Objects](https://www.datatables.net/manual/data/#Objects) section of their documentation, all we need to do is `data: "id"` instead of `data: null` in definition of the table. I have made this change.

**Review by atodorov — APPROVED** [review]
